### ISSUE TITLE
Hwk 2 Map not defined

### ISSUE THREAD

**Issue by njt2116** [ColumbiaJS/js-course#16]
I am having an issue understanding where this error is coming from.  The gulp file is telling me that Map() is not defined.  Are we not allowed to use these?   Here is the MDN reference:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Methods

I do see that it says that this offering is "experimental," but since this is not launching across various browsers, can we use it for homework?  If so, how? If not, what is a good alternative?

**Comment by jzf2101** [comment]
Which file is it on? Could you post the error?

On Feb 5, 2015, at 0:04, njt2116 notifications@github.com wrote:

I am having an issue understanding where this error is coming from. The
gulp file is telling me that Map() is not defined. Are we not allowed to
use these? Here is the MDN reference:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Methods

I do see that it says that this offering is "experimental," but since this
is not launching across various browsers, can we use it for homework? If
so, how? If not, what is a good alternative?

—
Reply to this email directly or view it on GitHub
https://github.com/ColumbiaJS/js-course/issues/16.

**Comment by levbrie** [comment]
@njt2116 @jzf2101 Unfortunately, Map is part of ES6, the next version of JavaScript.  The bad news is that you can't use map for your homework.  The good news is that you can use a plain old JavaScript object (called a POJO for short), something like `var map = {};` and for the purposes of this assignment (and nearly any kind of mapping you want to create), it will work great!
