### ISSUE TITLE
Team "Dirt Off Your Shoulder" Final Metier

### ISSUE THREAD

**Issue by ghost** [ColumbiaJS/js-course#9]
Team "Dirt Off Your Shoulder" is looking for members in order to solve one of Jay-Z's 99 problems using AngularJS.  The team name is negotiable.

Bio:
Name: Christopher Vasquez
UNI/Github Name: cev2107

Small Business Owner - Compulax LLC
Director of IT of two small private schools in Manhattan.
Current Full Time GS student.

Apache/Tomcat, Basic HTML/PHP/XML, C and Bash Scripting, Level 2 & 3 Network Management (Transport, Session, and Network level), VMWare ESXi 5.5 management, Debian/FreeBSD/RHEL Server Management, Windows 7 Pro and Mac OS X (10.6 - 10.10) deployment, OpenLDAP & Kerberos deployment

Next to ZERO experience with Javascript, but comfortable causing mayhem in production environments.

Project IDEA:  Moodle is a free open-source online learning platform/learning management system similar to Sakai (Courseworks) and Blackboard.  I am looking for a way to enhance the somewhat dull Moodle experience.  How? I'm not quite sure yet because we're only on week 2 of class.

Resources: I'm in the process of publishing an online Moodle server specifically for the duration of this project.  Any ideas are welcome!  Also, we'll need a DJ.

**Comment by jzf2101** [comment]
I'd be interested.

On Feb 3, 2015, at 9:53, "Chris V." notifications@github.com wrote:

Team "Dirt Off Your Shoulder" is looking for members in order to solve one
of Jay-Z's 99 problems using AngularJS. The team name is negotiable.

Bio:
Name: Christopher Vasquez
UNI/Github Name: cev2107

Small Business Owner - Compulax LLC
Director of IT of two small private schools in Manhattan.
Current Full Time GS student.

Apache/Tomcat, Basic HTML/PHP/XML, C and Bash Scripting, Level 2 & 3
Network Management (Transport, Session, and Network level),
Debian/FreeBSD/RHEL Server Management, Windows 7 Pro and Mac OS X (10.6 -
10.10) deployment, OpenLDAP & Kerberos deployment

Next to ZERO experience with Javascript, but comfortable causing mayhem in
production environments.

Project IDEA: Moodle is a free open-source online learning
platform/learning management system similar to Sakai (Courseworks) and
Blackboard. I am looking for a way to enhance the somewhat dull Moodle
experience. How? I'm not quite sure yet because we're only on week 2 of
class.

Resources: I'm in the process of publishing an online Moodle server
specifically for the duration of this project. Any ideas are welcome! Also,
we'll need a DJ.

—
Reply to this email directly or view it on GitHub
https://github.com/ColumbiaJS/js-course/issues/9.

**Comment by ghost** [comment]
Excellent.  We need one more.  Also, here's some more information about Moodle and guidelines for integrating JS with Moodle.  

https://docs.moodle.org/dev/JavaScript_guidelines

Javascript Moodle FAQ
https://docs.moodle.org/dev/Javascript_FAQ

Here's an example of a Javascript/Moodle project:
https://tracker.moodle.org/browse/MOBILE-184

**Comment by ghost** [comment]
@jzf2101 It seems we are only two.  Unless @levbrie is okay with this, we'll have to look elsewhere.

**Comment by jzf2101** [comment]
@levbrie we need to have people added to our group.

**Comment by ghost** [comment]
[Team "Dirty Off Your Shoulder" Group Repository](https://github.com/cev2107/Team_Dirt_Off_Your_Shoulder)

**Comment by ozzieba** [comment]
Alright, this sounds fun, I'll bite. I will be at the workshop on Sunday, so we can come up with a more concrete plan then, or let me know if you want to meet earlier.

**Comment by ghost** [comment]
Welcome @ozzieba I'll be there on Sunday as well.  I'll begin posting ideas on the repository.  I've invited both you and @jzf2101 as collaborators.  Please feel free to add, create issues, and go crazy on our repository.  I'm going to leave our group open for one more should anyone else need a group to join.

**Comment by ghost** [comment]
Alright, @ozzieba @jzf2101 It looks like it's us 3!  Let's do this!
Chris V.    cev2107
Jessica F. jzf21202
**\*             ozzieba

**Comment by ghost** [comment]
@ozzieba Make sure you add your information to the README.md file in our repository.  Or you can just give me your uni, name, school info here.

**Comment by levbrie** [comment]
@ozzieba @jzf2101 What is the status of this team?  It looks like the ghost repo has been deleted.  Please let me know what the final team roster is and what your repo is

**Comment by ozzieba** [comment]
@levbrie Our teammate dropped the course today, so as of now we're two... I am willing to continue with just 2, or join with others if spots exist. You should be CC'd on the email exchange from this morning (Columbia email), so any thoughts you have are welcome.
